version: '3.8'

networks:
  minha_rede:


services:
  mysql:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: websiteInfo
      MYSQL_USER: database
      MYSQL_PASSWORD: senha123
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin -uroot -proot ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - ./tabelas/01_consultores.sql:/docker-entrypoint-initdb.d/01_consultores.sql
      - ./tabelas/02_clientes.sql:/docker-entrypoint-initdb.d/02_clientes.sql
      - ./tabelas/03_imoveis.sql:/docker-entrypoint-initdb.d/03_imoveis.sql
      - ./tabelas/04_visitas.sql:/docker-entrypoint-initdb.d/04_visitas.sql
      - ./tabelas/06_favoritos.sql:/docker-entrypoint-initdb.d/06_favoritos.sql
      - ./my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
    networks:
      - minha_rede

  api:
    build: .
    container_name: node-api
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3001:3001"
    networks:
      - minha_rede
    environment:
      - JWT_SECRET=imoveis-sa
